<%- include('partials/header') %> 

<form action="/user/login" method="POST">
    <h2>Log in</h2>

    <label for="email">Email</label>
    <input required type="text" id="email" name="email">
    <div class="email error"></div>


    <label for="password">Password</label>
    <input required type="password" id="password" name="password">
    <div class="password error"></div>

    <button class="btn" type="submit">Log in</button>

</form>

<script>

    const form = document.querySelector('form');
    const emailError = document.querySelector('.email.error');
    const passwordError = document.querySelector('.password.error');

    form.addEventListener('submit', async (e) => {
        e.preventDefault();

        //reset 
        emailError.textContent = '';
        passwordError.textContent = '';

        const email = form.email.value;
        const password = form.password.value;

        try {
            const res = await fetch('/user/login', {
                method: 'POST',
                body: JSON.stringify({email, password}),
                headers: {'Content-Type': 'application/json'}
            });

            const data = await res.json();

            console.log(data);

            if(data.errors){
                emailError.textContent = data.errors.email;
                passwordError.textContent = data.errors.password;
            }

            if(data.user){
                console.log(data.user);
                location.assign('/');
            }            

        } 
        // The catch block only catches the error which is related to fetching the api...(Internal server error sorts...)
        catch (err) {
            console.log("Fetch Error: ",err);
        }


    });

</script>

<%- include('partials/footer') %> 