<%- include('partials/header') %>  

<form action="/user/signup" method="POST">
    <h2>Signup</h2>

    <label for="email">Email</label>
    <input required type="text" id="email" name="email">
    <div class="email error"></div>


    <label for="password">Password</label>
    <input required type="password" id="password" name="password">
    <div class="password error"></div>

    <button class="btn" type="submit">Sign up</button>

</form>

<script>

    const form = document.querySelector('form');
    const emailError = document.querySelector('.email.error');
    const passwordError = document.querySelector('.password.error');




    form.addEventListener('submit', async (e) => {
        e.preventDefault();

        emailError.textContent = '';
        passwordError.textContent = '';

        const email = form.email.value;
        const password = form.password.value;

        try {
            const response = await fetch('/user/signup', {
                method: 'POST',
                body: JSON.stringify({email, password}),
                headers: {'Content-Type': 'application/json'}
            });

            const data = await response.json();

            if(data.errors){
                emailError.textContent = data.errors.email;
                passwordError.textContent = data.errors.password;
            }

            if(data.user){
                location.assign('/');
            }

            console.log(data);

        } 
        // The catch block only catches the error which is related to fetching the api...(Internal server error sorts...)
        catch (err) {
            console.log("Error: ",err);
        }
    });

</script>

<%- include('partials/footer') %> 